Repository ie3-institute/powerFactory2psdm, pull requests merged in 2021-05, with the labels that each got.

#38 fix Jenkinsfile Rocket.Chat notification
  Jenkinsfile
Labels: bug

#43 State scalatest version to be ignored by dependabot explicitly
  .github/dependabot.yml
Labels: bug, dependencies

#29 Adjusted the Export script
  src/main/python/powerFactory2json/pf2json.py
  src/main/python/powerFactory2json/pf2jsonUtils.py
  src/main/scala/edu/ie3/powerFactory2psdm/model/powerfactory/PowerFactoryGrid.scala
Labels: enhancement
